update for python 3.10
py-vobject/vobject pull request #9
Opened 2024-02-23 14:23 UTC by da4089

See https://github.com/eventable/vobject/pull/184

2025-01-02 12:43 UTC, htgoebel requested changes

2025-01-02 12:43 UTC, htgoebel commented on vobject/icalendar.py
> +            return None
I suggest merging this clause into the next which has a comment about UTC.

2025-01-03 12:41 UTC, da4089 commented on vobject/icalendar.py
> +            return None
My patch was:
```
--- a/vobject/icalendar.py
+++ b/vobject/icalendar.py
@@ -332,7 +332,7 @@ class TimezoneComponent(Component):
         """

         # If tzinfo is UTC, we don't need a TZID
-        if tzinfo is None or (not allowUTC and tzinfo_eq(tzinfo, utc)):
+        if tzinfo is None or str(tzinfo) == 'UTC' or (not allowUTC and tzinfo_eq(tzinfo, utc)):
             return None

         # Try pytz tzid key
```

2025-01-06 19:30 UTC, htgoebel commented on vobject/icalendar.py
> +            return None
This is strange! Just to exclude a weird case: Have you tried
```
if str(tzinfo) == 'UTC' of tzinfo is None or (not allowUTC and tzinfo_eq(tzinfo, utc)):
```

2026-08-16 02:33 UTC, da4089 commented
I'm going to close this un-merged.

There's been other changes to this function, and it appears to be working for current CPython.  Please re-open if the issue happens again.

2026-08-16 02:33 UTC, closed without merging